### ISSUE TITLE
Doesnt start interactive. 

### ISSUE THREAD

**Issue by Xplodin** [funniray/Mixer#11]
[java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoClassDefFoundError: org/apache/http/client/HttpClient
[09:51:09] [Thread-137/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at com.mixer.api.MixerAPI.<init>(MixerAPI.java:52)
[09:51:09] [Thread-137/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at com.mixer.api.MixerAPI.<init>(MixerAPI.java:35)
[09:51:09] [Thread-137/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at pro.kdray.funniray.mixer.Main.startAll(Main.java:65)
[09:51:09] [Thread-137/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at pro.kdray.funniray.mixer.MixerForge.lambda$startMain$0(MixerForge.java:118)
[09:51:09] [Thread-137/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at java.lang.Thread.run(Thread.java:748)
[09:51:09] [Thread-137/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.ClassNotFoundException: org.apache.http.client.HttpClient
[09:51:09] [Thread-137/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[09:51:09] [Thread-137/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[09:51:09] [Thread-137/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
[09:51:09] [Thread-137/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[09:51:09] [Thread-137/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
[09:51:09] [Thread-137/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[09:51:09] [Thread-137/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[09:51:09] [Thread-137/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: ... 5 more

Upon any versions for this ore plugin, this is what console says when running /istart

**Comment by funniray** [comment]
Are you able to download the sponge version from the GitHub releases tab and try that? The sponge ore version might be broken.

**Comment by funniray** [comment]
https://github.com/funniray/Mixer/releases/download/1.2-29/mixer-sponge-1.2-29-all.jar

**Comment by Xplodin** [comment]
I tried all of them off github and ore.
Even tried the forge version. Mainly using spongeforge.

**Comment by Xplodin** [comment]
Just noticed something with my server running this plugin.
After the plugin enables I get this specific error:
[09:10:35] [Server thread/WARN] [Sponge]: /* Owning Mod/Plugin: mixer-sponge */
> [09:10:35] [Server thread/WARN] [Sponge]: /* Exception: */
> [09:10:35] [Server thread/WARN] [Sponge]: /* java.lang.NullPointerException: null */
> [09:10:35] [Server thread/WARN] [Sponge]: /* pro.kdray.funniray.mixer.MixerSponge.onServerStart(MixerSponge.java:167) */
> [09:10:35] [Server thread/WARN] [Sponge]: /* org.spongepowered.common.event.listener.GameStartedServerEventListener_MixerSponge_onServerStart3.handle(Unknown Source) */
> [09:10:35] [Server thread/WARN] [Sponge]: /* org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) */
> [09:10:35] [Server thread/WARN] [Sponge]: /* org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:381) */
> [09:10:35] [Server thread/WARN] [Sponge]: /* org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:454) */
> [09:10:35] [Server thread/WARN] [Sponge]: /* org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:415) */
> [09:10:35] [Server thread/WARN] [Sponge]: /* org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:259) */
> [09:10:35] [Server thread/WARN] [Sponge]: /* org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:378) */
> [09:10:35] [Server thread/WARN] [Sponge]: /* sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) */
> [09:10:35] [Server thread/WARN] [Sponge]: /* sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) */
> [09:10:35] [Server thread/WARN] [Sponge]: /* sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) */
> [09:10:35] [Server thread/WARN] [Sponge]: /* java.lang.reflect.Method.invoke(Method.java:498) */
> [09:10:35] [Server thread/WARN] [Sponge]: /* com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) */
> [09:10:35] [Server thread/WARN] [Sponge]: /* com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) */
> [09:10:35] [Server thread/WARN] [Sponge]: /* com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) */
> [09:10:35] [Server thread/WARN] [Sponge]: /* com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) */
> [09:10:35] [Server thread/WARN] [Sponge]: /* com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) */
> [09:10:35] [Server thread/WARN] [Sponge]: /* com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) */
> [09:10:35] [Server thread/WARN] [Sponge]: /* com.google.common.eventbus.EventBus.post(EventBus.java:217) */
> [09:10:35] [Server thread/WARN] [Sponge]: /* net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) */
> [09:10:35] [Server thread/WARN] [Sponge]: /* net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) */
> [09:10:35] [Server thread/WARN] [Sponge]: /* sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) */
> [09:10:35] [Server thread/WARN] [Sponge]: /* sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) */
> [09:10:35] [Server thread/WARN] [Sponge]: /* sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) */
> [09:10:35] [Server thread/WARN] [Sponge]: /* java.lang.reflect.Method.invoke(Method.java:498) */
> [09:10:35] [Server thread/WARN] [Sponge]: /* com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) */
> [09:10:35] [Server thread/WARN] [Sponge]: /* com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) */
> [09:10:35] [Server thread/WARN] [Sponge]: /* com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) */
> [09:10:35] [Server thread/WARN] [Sponge]: /* com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) */
> [09:10:35] [Server thread/WARN] [Sponge]: /* com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) */
> [09:10:35] [Server thread/WARN] [Sponge]: /* com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) */
> [09:10:35] [Server thread/WARN] [Sponge]: /* com.google.common.eventbus.EventBus.post(EventBus.java:217) */
> [09:10:35] [Server thread/WARN] [Sponge]: /* net.minecraftforge.fml.common.LoadController.redirect$forgeImpl$PostEvent$zza000(LoadController.java:568) */
> [09:10:35] [Server thread/WARN] [Sponge]: /* net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) */
> [09:10:35] [Server thread/WARN] [Sponge]: /* net.minecraftforge.fml.common.Loader.serverStarted(Loader.java:804) */
> [09:10:35] [Server thread/WARN] [Sponge]: /* net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:302) */
> [09:10:35] [Server thread/WARN] [Sponge]: /* net.minecraft.server.MinecraftServer.run(MinecraftServer.java:488) */
> [09:10:35] [Server thread/WARN] [Sponge]: /* java.lang.Thread.run(Thread.java:748) */
> [09:10:35] [Server thread/WARN] [Sponge]: /************************************************************************************************************************************************************************************************************************************************************************************************************************************************

**Comment by funniray** [comment]
Can you please tell me what Minecraft, Forge and sponge version you are
using?

**Comment by Xplodin** [comment]
mixer-sponge 1.2-29-all
spongeforge-1.12.2-2838-7.1.9-RC3980
forge 14.23.5.2847
