### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Artistic-Waffle** [funniray/Mixer#3]

**Comment by Artistic-Waffle** [comment]
22:30:52 [ALERT] java.lang.RuntimeException: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:439)
	at cn.nukkit.Server.enablePlugin(Server.java:670)
	at cn.nukkit.Server.enablePlugins(Server.java:659)
	at cn.nukkit.Server.<init>(Server.java:503)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
	at cn.nukkit.utils.ConfigSection.getList(ConfigSection.java:369)
	at cn.nukkit.utils.ConfigSection.getList(ConfigSection.java:358)
	at cn.nukkit.utils.ConfigSection.getStringList(ConfigSection.java:390)
	at cn.nukkit.utils.Config.getStringList(Config.java:358)
	at pro.kdray.funniray.mixer.MixerNukkit.onEnable(MixerNukkit.java:37)
	at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
	at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:113)
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:435)
	... 4 more

22:30:52 [INFO] Disabling Mixer v1.0.0
22:30:52 [ALERT] java.lang.NullPointerException
	at pro.kdray.funniray.mixer.MixerNukkit.onDisable(MixerNukkit.java:73)
	at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:91)
	at cn.nukkit.plugin.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:128)
	at cn.nukkit.plugin.PluginManager.disablePlugin(PluginManager.java:509)
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:441)
	at cn.nukkit.Server.enablePlugin(Server.java:670)
	at cn.nukkit.Server.enablePlugins(Server.java:659)
	at cn.nukkit.Server.<init>(Server.java:503)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)

**Comment by funniray** [comment]
I've been developing on Forge and not testing on Nukkit, give me a bit and I'll fix it in the next version. Thanks for reporting this to me!

**Comment by funniray** [comment]
Wait, can I confirm that you are using the default config, right?

**Comment by Artistic-Waffle** [comment]
Yes with a normal server nothing be changed

**Comment by Artistic-Waffle** [comment]
Still same  error

**Comment by funniray** [comment]
Try again with the newest version, it should be fixed

**Comment by Artistic-Waffle** [comment]
nope

**Comment by Artistic-Waffle** [comment]
21:20:53 [ALERT] java.lang.RuntimeException: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:439)
	at cn.nukkit.Server.enablePlugin(Server.java:670)
	at cn.nukkit.Server.enablePlugins(Server.java:659)
	at cn.nukkit.Server.<init>(Server.java:503)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
	at cn.nukkit.utils.ConfigSection.getList(ConfigSection.java:369)
	at cn.nukkit.utils.ConfigSection.getList(ConfigSection.java:358)
	at cn.nukkit.utils.ConfigSection.getStringList(ConfigSection.java:390)
	at cn.nukkit.utils.Config.getStringList(Config.java:358)
	at pro.kdray.funniray.mixer.MixerNukkit.onEnable(MixerNukkit.java:72)
	at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
	at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:113)
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:435)
	... 4 more

the disable part fix but not the enabling

**Comment by funniray** [comment]
Hmm, try deleting your config and trying again. I'm going to investigate more when I get home

**Comment by kd8lvt** [comment]
This seems like an operating system dependent problem. It appears Windows and Ubuntu are erroring, while everything else seems to work fine.

**Comment by funniray** [comment]
Okay, I got the config working for sure now **however** I'm unable to use Nukkit until the rewrite comes out due to Mixer not using log4j.

**Comment by funniray** [comment]
The rewrite uses log4j, so just wait for Mixer's rewrite to become stable and we'll be good
